services:
  postgres:
    image: postgres:15
    container_name: quarkus-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
      POSTGRES_DB: quarkus_db